### ISSUE TITLE
open and close a channel and reopen again cause error 

### ISSUE THREAD

**Issue by johnzhanghua** [mbroadst/qamqp#38] opened 2016-03-02 08:47 UTC
Hi I found there is a error when using the library in the following sequence.
1. client->connectToHost()
2. exchange = client->createExchange("myexchange");
   exchange->declare(QAmqpExchange::Topic);
3. queue = client->createQueue();
   queue->declare();
   queue->bind(exchange, "routingkey");
    queue->consume(QAmqpQueue::coNoAck);
4.  exchange->publish(message.toUtf8(), routingKey);

Then do the remove sequence as below:
1. queue->unbind(exchange, "routingkey");
   queue->close();
2.  exchange->close(); 
3. client->disconnectFromHost();

Then repeat 1-4 again. 
I got the following error log, could you please verify it is a bug or did I use the library wrong? 

Thank you very much. 

```
void QAmqpClientPrivate::_q_disconnect() already disconnected 
connecting to host:  "10.0.0.15" , port:  5672 
Connection: 
>> Start
>> version_major: 0
>> version_minor: 9
>> mechanisms:  ("PLAIN", "AMQPLAIN") 
>> locales: en_US
Connection: 
>> Tune
>> channel_max: 0
>> frame_max: 131072
>> heartbeat: 30
Connection: 
>> OpenOK
TRACE 2016-03-02T18:29:13.754 amqpmessageservice.cpp : 141 Connected : true  
TRACE 2016-03-02T18:29:13.754 amqpmessageservice.cpp : 177 Server connected   
Open channel #1
Channel#1:
>> OpenOK
declared exchange:  "myexchange" 
TRACE 2016-03-02T18:29:13.756 amqpmessageservice.cpp : 190 Declared : true  
TRACE 2016-03-02T18:29:13.756 amqpmessageservice.cpp : 210 Create queue  
Open channel #2
Channel#2:
>> OpenOK
declared queue:  "" 
message count 0
Consumer count: 0
TRACE 2016-03-02T18:29:13.762 amqpmessageservice.cpp : 227 Queue declared  
void QAmqpQueuePrivate::bindOk(const QAmqpMethodFrame&) bound to exchange 
void QAmqpQueuePrivate::bindOk(const QAmqpMethodFrame&) bound to exchange 
void QAmqpQueuePrivate::bindOk(const QAmqpMethodFrame&) bound to exchange 
TRACE 2016-03-02T18:29:13.767 amqpmessageservice.cpp : 237 Queue bound  
void QAmqpQueuePrivate::deliver(const QAmqpMethodFrame&) 

void QAmqpQueuePrivate::unbindOk(const QAmqpMethodFrame&) unbound from exchange 
void QAmqpQueuePrivate::unbindOk(const QAmqpMethodFrame&) unbound from exchange 
void QAmqpQueuePrivate::unbindOk(const QAmqpMethodFrame&) unbound from exchange 
TRACE 2016-03-02T18:29:18.129 amqpmessageservice.cpp : 254 Close queue  
Channel#2:
TRACE 2016-03-02T18:29:18.132 amqpmessageservice.cpp : 257 Remove queue  
TRACE 2016-03-02T18:29:18.132 amqpmessageservice.cpp : 202 Close exchange  
Channel#1:
TRACE 2016-03-02T18:29:18.132 amqpmessageservice.cpp : 169 Disconnect from Host  
Connection: 
void QAmqpClientPrivate::closeOk(const QAmqpMethodFrame&) received 
TRACE 2016-03-02T18:29:18.132 amqpmessageservice.cpp : 75 Connect connected :  false From: QAmqpClient(0x9a5e1b8)  
exchange  "myexchange"  disconnected 
connecting to host:  "10.0.0.15" , port:  5672 
Connection: 
>> Start
>> version_major: 0
>> version_minor: 9
>> mechanisms:  ("PLAIN", "AMQPLAIN") 
>> locales: en_US
Connection: 
>> Tune
>> channel_max: 0
>> frame_max: 131072
>> heartbeat: 30
Connection: 
>> OpenOK
Open channel #1
Open channel #2
Channel#1:
>> OpenOK
TRACE 2016-03-02T18:29:18.170 amqpmessageservice.cpp : 141 Connected : true  
TRACE 2016-03-02T18:29:18.170 amqpmessageservice.cpp : 177 Server connected   
Channel#2:
>> OpenOK
declared exchange:  "myexchange" 
TRACE 2016-03-02T18:29:18.170 amqpmessageservice.cpp : 190 Declared : true  
TRACE 2016-03-02T18:29:18.170 amqpmessageservice.cpp : 210 Create queue  
Open channel #1
Connection: 
>> CLOSE
>> code: 504
>> text: CHANNEL_ERROR - second 'channel.open' seen
>> class-id: 20
>> method-id: 10
TRACE 2016-03-02T18:29:18.171 amqpmessageservice.cpp : 75 Connect connected :  false From: QAmqpClient(0x9a5e1b8)  
exchange  "station_master"  disconnected 
socket error:  "The remote host closed the connection" 
ERROR 2016-03-02T18:29:18.171 amqpmessageservice.cpp : 158 Client connect error QAbstractSocket::RemoteHostClosedError  
TRACE 2016-03-02T18:29:18.672 amqpmessageservice.cpp : 220 Queue declare timeout  
TRACE 2016-03-02T18:29:18.672 amqpmessageservice.cpp : 227 Queue declared  
TRACE 2016-03-02T18:29:19.172 amqpmessageservice.cpp : 234 Queue bind timeout  
```

**Comment by mbroadst** [comment] 2016-03-02 22:04
@johnzhanghua can you possibly provide an actual sample piece of code? I haven't used this library in almost two years, so you'll have to bear with me.

**Comment by mbroadst** [comment] 2016-03-02 22:06
what seems to be happening is that the remote host is closing the attempts to recreate channels for the queue/exchange because the library is reusing a channel number. This should be specific to the session, and therefore a disconnect should have cleared the remote variables (like the local side seems to be doing), allowing us to revert back to 0 for channel ordering. 

I don't really see in your log there the disconnect. I see the unbind's for queue and exchange, and then I see a reconnect.

**Comment by johnzhanghua** [comment] 2016-03-02 23:45
testReconnection.h

#ifndef TESTRECONNECTION_H
#define TESTRECONNECTION_H

#include <QObject>

class testReconnection : public QObject
{
    Q_OBJECT

public:
    testReconnection();
    void testReconnect();
    bool waitForSignal(QObject *obj, const char *signal, int msec = 300);

private slots:
    void messageReceived();
};

#endif // TESTRECONNECTION_H


testReconnection.cpp 
#include "testreconnection.h"

#include <QCoreApplication>
#include <QStringList>
#include <QDebug>
#include <QHostInfo>
#include <QAbstractSocket>
#include "qamqpclient.h"
#include "qamqpexchange.h"
#include "qamqpqueue.h"
#include "QTimer"

testReconnection::testReconnection()
{
}

void testReconnection::testReconnect()
{
    QAmqpClient* m_client = new QAmqpClient();

    // do connection
    //m_client->setUsername("john");
    //m_client->setPassword("john");
    m_client->setHost("10.0.0.15");

    m_client->connectToHost();
    bool connected =  waitForSignal(m_client, SIGNAL(connected())) ;
    qDebug("Connected %d:", connected);

    // create & declare exchange to send message
    QAmqpExchange* m_exchange = m_client->createExchange("myexchange");
    m_exchange->declare(QAmqpExchange::Topic);

    bool declared =  waitForSignal(m_exchange, SIGNAL(declared()));
    qDebug ("Declared : %d" , declared) ;

    // creat another channel to receive message
    QAmqpQueue* m_recvQueue = m_client->createQueue();
    connect(m_recvQueue, SIGNAL(messageReceived()), this, SLOT(messageReceived()));
    m_recvQueue->declare();

    if ( ! waitForSignal(m_recvQueue, SIGNAL(declared()))){
        qDebug  ("Queue declare timeout") ;
        return ;
    }
    // bind the receive channel for income message routing key
    m_recvQueue->bind(m_exchange, "routingKeyin");
    if (! waitForSignal(m_recvQueue, SIGNAL(bound()))){
        qDebug ("Queue bind timeout");
        return ;
    }
    qDebug ( "Queue bound" );
    m_recvQueue->consume(QAmqpQueue::coNoAck);

    // send a message
    m_exchange->publish("test message", "routingKeyout");



    // disconnection process below

    // unbind and remove recv queue
    m_recvQueue->unbind(m_exchange, "routingKeyin");
    waitForSignal(m_recvQueue, SIGNAL(unbound()));

    qDebug ( "Close queue" );
    m_recvQueue->close();
    waitForSignal(m_recvQueue, SIGNAL(closed()));

    qDebug ( "Close exchange" );
    m_exchange->close();
    waitForSignal(m_exchange, SIGNAL(closed()));

    // disconnect
    m_client->disconnectFromHost();
    waitForSignal(m_client,SIGNAL(disconnected()));



    // repeat the connection and create again here
    // just copy and past

    // do connection
    //m_client->setUsername("john");
    //m_client->setPassword("john");
    m_client->setHost("10.0.0.15");

    m_client->connectToHost();
    connected =  waitForSignal(m_client, SIGNAL(connected())) ;
    qDebug ( "Connected : %d" , connected );

    // create & declare exchange to send message
    m_exchange = m_client->createExchange("myexchange");
    m_exchange->declare(QAmqpExchange::Topic);

    declared =  waitForSignal(m_exchange, SIGNAL(declared()));
    qDebug ( "Declared : %d" , declared ) ;

    // creat another channel to receive message
    m_recvQueue = m_client->createQueue();
    connect(m_recvQueue, SIGNAL(messageReceived()), this, SLOT(messageReceived()));
    m_recvQueue->declare();

    if ( ! waitForSignal(m_recvQueue, SIGNAL(declared()))){
        qDebug ("Queue declare timeout") ;
        return ;
    }
    // bind the receive channel for income message routing key
    m_recvQueue->bind(m_exchange, "routingKeyin");
    if (! waitForSignal(m_recvQueue, SIGNAL(bound()))){
        qDebug ( "Queue bind timeout" );
        return ;
    }
    qDebug ( "Queue bound" );
    m_recvQueue->consume(QAmqpQueue::coNoAck);

    // send a message
    m_exchange->publish("test message", "routingKeyout");

    // delete the client
    delete m_exchange;
    delete m_recvQueue;
    delete m_client;

}

bool testReconnection::waitForSignal(QObject *obj, const char *signal, int msec)
{
    QEventLoop loop;
    QTimer timer;
    connect(obj,signal, &loop, SLOT(quit()));
    connect(&timer, SIGNAL(timeout()), &loop, SLOT(quit()));

    timer.setSingleShot(true);
    timer.start(msec);
    loop.exec();
    return timer.isActive();
}

void testReconnection::messageReceived()
{

}


in main.cpp

 testReconnection* test = new testReconnection();
 test->testReconnect();

Here is the logs:
connecting to host:  "10.0.0.15" , port:  5672 
Connection: 
>> Start
>> version_major: 0
>> version_minor: 9
>> mechanisms:  ("PLAIN", "AMQPLAIN") 
>> locales: en_US
Connection: 
>> Tune
>> channel_max: 0
>> frame_max: 131072
>> heartbeat: 60
Connection: 
>> OpenOK
Connected 1:
Open channel #1
Channel#1:
>> OpenOK
declared exchange:  "myexchange" 
Declared : 1
Open channel #2
Channel#2:
>> OpenOK
declared queue:  "" 
message count 0
Consumer count: 0
void QAmqpQueuePrivate::bindOk(const QAmqpMethodFrame&) bound to exchange 
Queue bound
consume ok:  "amq.gen-C7K7a_UXgQXsFitDJdOxqQ" 
consumer tag = amq.ctag-MCDKOCwTZWZ2Y2xvWQJ6Ew
void QAmqpQueuePrivate::unbindOk(const QAmqpMethodFrame&) unbound from exchange 
Close queue
Channel#2:
Close exchange
Channel#1:
Connection: 
void QAmqpClientPrivate::closeOk(const QAmqpMethodFrame&) received 
exchange  "myexchange"  disconnected 
connecting to host:  "10.0.0.15" , port:  5672 
Connection: 
>> Start
>> version_major: 0
>> version_minor: 9
>> mechanisms:  ("PLAIN", "AMQPLAIN") 
>> locales: en_US
Connection: 
>> Tune
>> channel_max: 0
>> frame_max: 131072
>> heartbeat: 60
Connection: 
>> OpenOK
Open channel #1
Open channel #2
Channel#1:
>> OpenOK
Connected : 1
Channel#2:
>> OpenOK
declared exchange:  "myexchange" 
Declared : 1
Open channel #1
Connection: 
>> CLOSE
>> code: 504
>> text: CHANNEL_ERROR - second 'channel.open' seen
>> class-id: 20
>> method-id: 10
exchange  "myexchange"  disconnected 
socket error:  "The remote host closed the connection" 
Queue declare timeout
void QAmqpClientPrivate::sendFrame(const QAmqpFrame&) socket not connected:  QAbstractSocket::UnconnectedState 
void QAmqpClientPrivate::sendFrame(const QAmqpFrame&) socket not connected:  QAbstractSocket::UnconnectedState

**Comment by johnzhanghua** [comment] 2016-03-04 07:44
@mbroadst , source code provided.

**Comment by mbroadst** [comment] 2016-03-04 15:25
@johnzhanghua hey sorry for the delay here. So what's going on here is that QAMQP, by default, attempts to reattach existing "channels" when you reconnect the client. So when you call your reconnect code, and try to recreate the exchange and queue, it's already doing that for you behind the scenes for the existing channels.

This is indeed a bug because clearly you are fully disconnecting the client and trying to create new channels completely (ignoring your previously created ones).  I've added your case to the auto tests and I'll push out a fix shortly.

**Comment by mbroadst** [comment] 2016-03-04 18:07
@johnzhanghua I added a bunch of useful debug information for frame-level operations to the library. Upon a second glance, I'm going to go ahead and say this is "by design". 

What we have internally is a caching mechanism for queues and exchanges, so there are a few things going on here when you disconnect:

  * you explicitly close the exchange and queue
  * then you disconnect
  * then you reconnect the same client
  * the client's internal socket is connected to the `open` methods of the two existing channels (queue and exchange)
  * when you call `createQueue` or `createExchange` on the client, it's actually returning a point to the already existing queue/exchange, so when you call declare on it again it's doing double-duty and that's why you see the error message you see

**Comment by johnzhanghua** [comment] 2016-03-06 23:03
@mbroadst I added the below code, but it did not help. 
    m_recvQueue->remove();
    waitForSignal((m_recvQueue), SIGNAL(removed()));
    m_exchange->remove();
    waitForSignal(m_exchange, SIGNAL(removed()));

I have a user case that the user may  dynamically change the RabbitMQ server settings, which needs a disconnection and reconnection I think . How could I remove the internally cached channels?

**Comment by johnzhanghua** [comment] 2016-03-08 05:52
@mbroadst Any comments about do a internal cached channels clean up?

**Comment by mbroadst** [comment] 2016-03-08 13:49
@johnzhanghua `QAmqpClient` has an internal cache as I mentioned earlier, and that actually tracks the lifetime of the channels themselves. So, if you want to explicitly remove the channel you simply need to delete it (or rather, since it's a QObject you should be using `deleteLater`). I've shown an example in the tests here: https://github.com/mbroadst/qamqp/commit/8109e5343cc5a39fada4fe6cc735880e424a9384

Specifically you would change your code: 
```
m_recvQueue->remove();
waitForSignal((m_recvQueue), SIGNAL(removed()));
m_exchange->remove();
waitForSignal(m_exchange, SIGNAL(removed()));
``

to:
```
m_recvQueue->remove();
waitForSignal((m_recvQueue), SIGNAL(removed()));
m_recvQueue->deleteLater();

m_exchange->remove();
waitForSignal(m_exchange, SIGNAL(removed()));
m_exchange->deleteLater();
```

**Comment by johnzhanghua** [comment] 2016-03-09 02:32
Thanks, that works. But there is an error log there :
>> text: CHANNEL_ERROR - expected 'channel.open'

onnecting to host:  "10.0.0.13" , port:  5672 
Connection: 
>> Start
>> version_major: 0
>> version_minor: 9
>> mechanisms:  ("PLAIN", "AMQPLAIN") 
>> locales: en_US
Connection: 
>> Tune
>> channel_max: 0
>> frame_max: 131072
>> heartbeat: 60
Connection: 
>> OpenOK
Connected : 1
Open channel #1
Channel#1:
>> OpenOK
declared exchange:  "myexchange" 
Declared : 1
Open channel #2
Channel#2:
>> OpenOK
declared queue:  "" 
message count 0
Consumer count: 0
void QAmqpQueuePrivate::bindOk(const QAmqpMethodFrame&) bound to exchange 
Queue bound
consume ok:  "amq.gen-gPEMOCFzlx-uoMUJdSCRiA" 
consumer tag = amq.ctag-NL8eOyOcX4eAstOVlOVzVg
void QAmqpQueuePrivate::unbindOk(const QAmqpMethodFrame&) unbound from exchange 
Close queue
Channel#2:
Connection: 
>> CLOSE
>> code: 504
>> text: CHANNEL_ERROR - expected 'channel.open'
>> class-id: 50
>> method-id: 40
exchange  "myexchange"  disconnected 
socket error:  "The remote host closed the connection" 
Close exchange
void QAmqpClientPrivate::sendFrame(const QAmqpFrame&) socket not connected:  QAbstractSocket::UnconnectedState 
connecting to host:  "10.0.0.13" , port:  5672 
Connection: 
>> Start
>> version_major: 0
>> version_minor: 9
>> mechanisms:  ("PLAIN", "AMQPLAIN") 
>> locales: en_US
Connection: 
>> Tune
>> channel_max: 0
>> frame_max: 131072
>> heartbeat: 60
Connection: 
>> OpenOK
Connected : 1
Open channel #1
Channel#1:
>> OpenOK
declared exchange:  "myexchange" 
Declared : 1
Open channel #2
Channel#2:
>> OpenOK
declared queue:  "" 
message count 0
Consumer count: 0
void QAmqpQueuePrivate::bindOk(const QAmqpMethodFrame&) bound to exchange 
Queue bound
consume ok:  "amq.gen-LFKDJnqYegfLclPf8Habug" 
consumer tag = amq.ctag-9i9oURJwhCO8-n2sBTBV-A

**Comment by mbroadst** [comment] 2016-03-09 13:59
@johnzhanghua I've pushed another commit here: https://github.com/mbroadst/qamqp/commit/3b4f6d770911cc1593c6eba814a1fbce1edb92e5, which is your exact code from above working with `deleteLater()` added. If you are running into another error, you will have to provide updated code

**Closed** 2016-12-10 03:41 UTC
